version: "3.8"

services:
  blogging-db:
    image: postgres:13
    container_name: my_chat_app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vision2030
      POSTGRES_DB: gideon

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  my_postgres_data:
