version: "3.8"

services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vision2030
      POSTGRES_DB: gideon
    networks:
      - contentBlog
  shopping-db:
    image: postgres:13
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vision2030
      POSTGRES_DB: gideon
    networks:
      - contentBlog
  test-db:
    image: postgres:13
    ports:
      - 5435:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vision2030
      POSTGRES_DB: contento
    networks:
      - contentBlog
networks:
  contentBlog:
